### ISSUE TITLE
Config question

### ISSUE THREAD

**Issue by mcindea** [carrotquest/django-clickhouse#10]
First of all thank you for all the work, you've done tremendous amount of dedication!

I want to ask a n00b question, I am new to Django, and I can't figure out how to set it up in settings.py since DATABASES and CLICKHOUSE_DATABASES are different, and I can't figure out the Django engine I should use. I've went through the PR with docs, but still couldn't figure it out.
Can you please give me a hint?

Thank you!

**Comment by M1ha-Shvn** [comment]
Hi.
First of all, `DATABASES` and `CLICKHOUSE_DATABASES` in django settings are not somehow connected to each other.
`DATABASES` parameter configures databases, used with django QuerySet/Model system. It has `engine` attribute, which tells django what driver it should use for this connection (PostgreSQL, MySQL, Oracle etc). You can read more about it [here](https://docs.djangoproject.com/en/3.0/ref/databases/).
`CLICKHOUSE_DATABASES` is a parameter, introduced by this library. It determines connections, which can be used with this library [QuerySet](https://github.com/carrotquest/django-clickhouse/blob/docs-and-compatibility/docs/models.md#clickhousemodel)/[ClickHouseModel](https://github.com/carrotquest/django-clickhouse/blob/docs-and-compatibility/docs/models.md#clickhousemodel) system only. It's structure is very much like `DATABASES`. But attributes are different (they are described [here](https://github.com/carrotquest/django-clickhouse/blob/docs-and-compatibility/docs/configuration.md#clickhouse_databases)):
- It doesn't need `engine` as the only database it works with is ClickHouse.
- The most part of attributes are [infi.clickhouse_orm Database(**kwargs) object kwargs](https://github.com/Infinidat/infi.clickhouse_orm/blob/develop/docs/class_reference.md#database)
- `migrate` attribute, introduced by library in order to have ability to disable migrations for connection (for instance, if you have multiple connections to single database)

Unlike django, [ClickHouse Engine](https://github.com/carrotquest/django-clickhouse/blob/docs-and-compatibility/docs/models.md#engines) defines mechanics of each table work. You can read more about it [here](https://clickhouse.yandex/docs/en/operations/table_engines/). In this library it is set as [ClickHouseModel](https://github.com/carrotquest/django-clickhouse/blob/docs-and-compatibility/docs/models.md#clickhousemodel) attribute.

**Comment by M1ha-Shvn** [comment]
I close issue, for no response. You may reopen issue, if you have more questions.
